### Get token (stub)
POST http://localhost:8081/v1/auth/token
Content-Type: application/json

{
  "client_id": "test_client",
  "scopes": ["flags:rw"]
}

### Get JWT token
POST http://localhost:8081/v1/auth/token
Content-Type: application/json

{
  "client_id": "test_client",
  "scopes": ["flags:rw"]
}

### Verify JWT token

POST http://localhost:8081/v1/auth/verify
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X2NsaWVudCIsInNjb3BlcyI6WyJmbGFnczpydyJdLCJpYXQiOjE3NTk4MTMxODguNDUzMzk2LCJleHAiOjE3NTk4MzQ3ODguNDUzMzk2fQ.t1sZ03aHWhLAngo0Vxn-fTmwoDXrSsAyOu1f30xOp7A"
}

### Create flag
POST http://localhost:8081/v1/flags
Content-Type: application/json
X-Tenant-ID: ABC
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X2NsaWVudCIsInNjb3BlcyI6WyJmbGFnczpydyJdLCJpYXQiOjE3NTk4MTMxODguNDUzMzk2LCJleHAiOjE3NTk4MzQ3ODguNDUzMzk2fQ.t1sZ03aHWhLAngo0Vxn-fTmwoDXrSsAyOu1f30xOp7A

{
  "key": "test110",
  "description": "New checkout flow",
  "state": "on",
  "variants": [
    {"key": "control", "weight": 50},
    {"key": "treatment", "weight": 50}
  ],
  "rules": [
    {
      "id": "r1",
      "order": 1,
      "when": {"percentage": 50},
      "rollout": {
        "distribution": [
          {"key": "control", "weight": 50},
          {"key": "treatment", "weight": 50}
        ]
      }
    }
  ]
}

###get flag
GET http://localhost:8081/v1/flags/test106
X-Tenant-ID: ABC
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X2NsaWVudCIsInNjb3BlcyI6WyJmbGFnczpydyJdLCJpYXQiOjE3NTk4MTMxODguNDUzMzk2LCJleHAiOjE3NTk4MzQ3ODguNDUzMzk2fQ.t1sZ03aHWhLAngo0Vxn-fTmwoDXrSsAyOu1f30xOp7A

###update flag

PUT http://localhost:8081/v1/flags/test109
Content-Type: application/json
X-Tenant-ID: ABC
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X2NsaWVudCIsInNjb3BlcyI6WyJmbGFnczpydyJdLCJpYXQiOjE3NTk4MTMxODguNDUzMzk2LCJleHAiOjE3NTk4MzQ3ODguNDUzMzk2fQ.t1sZ03aHWhLAngo0Vxn-fTmwoDXrSsAyOu1f30xOp7A

{
  "key": "test109",
  "description": "Updated checkout flow",
  "state": "off",
  "variants": [
    {"key": "control", "weight": 40},
    {"key": "treatment", "weight": 60}
  ],
  "rules": [
    {
      "id": "r1",
      "order": 1,
      "when": {"percentage": 100},
      "rollout": {
        "distribution": [
          {"key": "control", "weight": 40},
          {"key": "treatment", "weight": 60}
        ]
      }
    }
  ]
}

###delete
DELETE http://localhost:8081/v1/flags/test106
X-Tenant-ID: ABC
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X2NsaWVudCIsInNjb3BlcyI6WyJmbGFnczpydyJdLCJpYXQiOjE3NTk4MTMxODguNDUzMzk2LCJleHAiOjE3NTk4MzQ3ODguNDUzMzk2fQ.t1sZ03aHWhLAngo0Vxn-fTmwoDXrSsAyOu1f30xOp7A

### Create flag

POST http://localhost:8081/v1/flags
Content-Type: application/json
X-Tenant-ID: acme
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X2NsaWVudCIsInNjb3BlcyI6WyJmbGFnczpydyJdLCJpYXQiOjE3NTk3MjIwMDUuMDczNzc1LCJleHAiOjE3NTk3NDM2MDUuMDczNzc1fQ.eKYv2bahohB_d2MqD0838yWWRl4SXS9PkcIKjk2fgAE

{
  "key": "new_checkout126",
  "description": "New checkout flow",
  "state": "on",
  "variants": [
    {"key": "control", "weight": 50},
    {"key": "treatment", "weight": 50}
  ],
  "rules": [
    {
      "id": "r1",
      "order": 1,
      "when": {"percentage": 50},
      "rollout": {
        "distribution": [
          {"key": "control", "weight": 50},
          {"key": "treatment", "weight": 50}
        ]
      }
    }
  ]
}


### Create Segment
POST http://localhost:8081/v1/segments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X2NsaWVudCIsInNjb3BlcyI6WyJmbGFnczpydyJdLCJpYXQiOjE3NTk4MTg2NTcuMTkzMDYxLCJleHAiOjE3NTk4NDAyNTcuMTkzMDYxfQ.s1lJU_YGKc_WiclDKNJWySYNJ6G6GPyBXpTFlfRqNG0
x-tenant-id: ABC

{
  "key": "canada_ios_users_1",
  "criteria": {
    "all": [
      {"attr": {"country": "CA"}},
      {"attr": {"os": "iOS"}}
    ]
  }
}

### List Segments
GET http://localhost:8081/v1/segments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X2NsaWVudCIsInNjb3BlcyI6WyJmbGFnczpydyJdLCJpYXQiOjE3NTk4MTg2NTcuMTkzMDYxLCJleHAiOjE3NTk4NDAyNTcuMTkzMDYxfQ.s1lJU_YGKc_WiclDKNJWySYNJ6G6GPyBXpTFlfRqNG0
x-tenant-id: ABC

### Get Segment
GET http://localhost:8081/v1/segments/canada_ios_users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X2NsaWVudCIsInNjb3BlcyI6WyJmbGFnczpydyJdLCJpYXQiOjE3NTk4MTg2NTcuMTkzMDYxLCJleHAiOjE3NTk4NDAyNTcuMTkzMDYxfQ.s1lJU_YGKc_WiclDKNJWySYNJ6G6GPyBXpTFlfRqNG0
x-tenant-id: ABC

### Update Segment
PUT http://localhost:8081/v1/segments/canada_ios_users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X2NsaWVudCIsInNjb3BlcyI6WyJmbGFnczpydyJdLCJpYXQiOjE3NTk4MTg2NTcuMTkzMDYxLCJleHAiOjE3NTk4NDAyNTcuMTkzMDYxfQ.s1lJU_YGKc_WiclDKNJWySYNJ6G6GPyBXpTFlfRqNG0
x-tenant-id: ABC

{
  "key": "canada_ios_users",
  "criteria": {
    "any": [
      {"attr": {"country": "CA"}},
      {"attr": {"country": "US"}}
    ]
  }
}


### Delete Segment
DELETE http://localhost:8081/v1/segments/canada_ios_users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X2NsaWVudCIsInNjb3BlcyI6WyJmbGFnczpydyJdLCJpYXQiOjE3NTk4MTg2NTcuMTkzMDYxLCJleHAiOjE3NTk4NDAyNTcuMTkzMDYxfQ.s1lJU_YGKc_WiclDKNJWySYNJ6G6GPyBXpTFlfRqNG0
x-tenant-id: ABC


### list audit

GET http://localhost:8081/v1/audit
Host: your-api-domain.com
Accept: application/json
X-Tenant-ID: ABC
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X2NsaWVudCIsInNjb3BlcyI6WyJmbGFnczpydyJdLCJpYXQiOjE3NTk4MTg2NTcuMTkzMDYxLCJleHAiOjE3NTk4NDAyNTcuMTkzMDYxfQ.s1lJU_YGKc_WiclDKNJWySYNJ6G6GPyBXpTFlfRqNG0

